services:
  minecraft-server:
    image: itzg/minecraft-server
    container_name: mc_servidor
    restart: always
    ports:
      - "25565:25565"
      - "25575:25575"
    environment:
      EULA: "TRUE"
      TYPE: PAPER
      VERSION: 1.20.4
      INIT_MEMORY: 4G
      MAX_MEMORY: 5G
      JVM_XX_OPTS: >-
        -XX:+UseG1GC
        -XX:+ParallelRefProcEnabled
        -XX:MaxGCPauseMillis=200
        -XX:+UnlockExperimentalVMOptions
        -XX:+DisableExplicitGC
        -XX:+AlwaysPreTouch
        -XX:G1NewSizePercent=30
        -XX:G1MaxNewSizePercent=40
        -XX:G1HeapRegionSize=8M
        -XX:G1ReservePercent=20
        -XX:G1HeapWastePercent=5
        -XX:G1MixedGCCountTarget=4
        -XX:InitiatingHeapOccupancyPercent=15
        -XX:G1MixedGCLiveThresholdPercent=90
        -XX:G1RSetUpdatingPauseTimePercent=5
        -XX:+PerfDisableSharedMem
        -XX:MaxTenuringThreshold=1
      JVM_OPTS: "-Dusing.aikars.flags=https://mcflags.emc.gs -Daikars.new.flags=true"
      LEVEL: "The Shit"
      ONLINE_MODE: "FALSE"
      ENABLE_RCON: "true"
      RCON_PORT: 25575
      RCON_PASSWORD: mcpassword
    volumes:
      - ./datos_mc:/data

  playit-agent:
    image: ghcr.io/playit-cloud/playit-agent:0.17
    container_name: mc_tunel_red
    restart: always
    network_mode: host
    env_file:
      - .env